### ISSUE TITLE
New brand name for the project?

### ISSUE THREAD

**Issue by HLFH** [fiddur/some-comments#11]
Hi,

The name *some-comments* seems difficult to remember. For SEO, when you type *some comments github* on Google, you don't directly find your project. Because *some comments* keyword is too generic. So, maybe, it would be a good idea, to find a better name for the project. What do you think?

**Comment by fiddur** [comment]
It might.  I've gotten used to *Some comments* now, but I agree with the problem.

Fill in suggestions in this issue :)

**Comment by HLFH** [comment]
Ghost Social, Ghost Comments, AnonPlus (was the name of a social project & alternative to FB backed by Anonymous entity, but it was soon discontinued, so in memory of that), Textalk (in memory of a famous company), Talkative, Wendy (because there is Casper the Friendly Ghost, there is already Ghost, the theme Casper, so [why not Wendy, the friend of Casper](https://en.wikipedia.org/wiki/Casper_Meets_Wendy)?)

**Comment by fiddur** [comment]
I don't want the name to tie it specifically to Ghost, nor to anonymity, loosely related to Ghost like Wendy, but with something saying what it is (I like being able to guess what software does from the name, like mysql or mariadb, and unlike cassandra…).  Wendy Commenting?

**Comment by Dervisevic** [comment]
Commentastic, Commtastic, Commie, ComCom, CommentsPlus, Cormier, CommercialCommentsCom.

I like @HLFH's suggestion of Talkative. Or Textalkative ;)

**Comment by erikedhagen** [comment]
Commentity
Commenity
Commense (comment / commence / common sense ?? )
Commant
Comma
Commerts
Oponion (onion themed)
Talkatom
Commentalk
Commentee (comment / commitee)

**Comment by HLFH** [comment]
Maybe @ctrlcctrlv got some ideas. 

If you don't want a project name related to Ghost (so no Wendy Commenting I guess), nor to anonymity, and if you want a pragmatical name saying what it is, the name should keep "comment" or "comments" in its name, we could also choose LibreComments (or LibreComment), so there, we just replace the generic "some". It's an inspiration from the name LibreOffice. Or yes "Talkative" or the others proposed by @Dervisevic and @erikedhagen

**Comment by fiddur** [comment]
A name *loosely* connected to Ghost is okay, but not so strongly as "Ghost Commenting".  "Wendy Commentastic"?

I really liked Ouija, but that's taken already (for talking to Ghosts…).

Talkative Wendy
Wendy Comments / Commenting

**Comment by fiddur** [comment]
Commentful
Commentozia
Cozymentia

**Comment by HLFH** [comment]
Hi @halfdan from Ghost.org, could we fully take the name Ouija?

**Comment by fiddur** [comment]
It would be confusing to take a name from another commenting system, even if it appears to be dead…

**Comment by ostPavel** [comment]
There's always an option to bookmark a repo =P
**some-comments** (or **simple comments**) sounds like a perfect name, in my opinion. Gets straight to the point.

Regarding the SEO - Google's Pagerank depends mostly on backlinks, afaik. So if everyone using **some-comments** for their website/project/blog links to this repo, it might help.

**Comment by fiddur** [comment]
The link to this repo is automatically there under the comments (if you use the included client.js).  Perhaps the name is good enough and it's a bit late to change anyway…

**Comment by fiddur** [comment]
I thought a bit about **libre comments** or something pointing out the AGPL and freedom from other systems, but I think I'll stick with **some comment** anyway now.  It'll have to catch on!
