### ISSUE TITLE
Error: "Could not register report from file html.js"

### ISSUE THREAD

**Issue by ostPavel** [fiddur/some-comments#8]
Attempting to install **some-comments** to a Ghost-powered blog.

System is Ubuntu 14.04 with Ghost 0.7 (with root access)
Node v0.12.7

My steps, done as a root user:
* Clone some-comments repo
* change directory, *npm install*
* copy example config file, edit config.js
 * there I change random seed (secret) phrase and add email credentials; I skip migration phase cause I have nothing to migrate (can this be the cause of the issue?)
* *node index.js* gives the following error:

`Error: Could not register report from file html.js`
`    at /var/www/some-comments/node_modules/istanbul/lib/util/factory.js:60:27`
`    at Array.forEach (native)`
`    at Object.Factory.loadStandard (/var/www/some-comments/node_modules/istanbul/lib/util/factory.js:53:29)`
`    at Object.<anonymous> (/var/www/some-comments/node_modules/istanbul/lib/register-plugins.js:11:8)`
`    at Module._compile (module.js:460:26)`
`    at Object.Module._extensions..js (module.js:478:10)`
`    at Module.load (module.js:355:32)`
`    at Function.Module._load (module.js:310:12)`
`    at Module.require (module.js:365:17)`
`    at require (module.js:384:17)`

*npm list* command shows missing dependencies, also, some of the node packages have "unmet dependencies"

**Comment by fiddur** [comment]
Migration is used for initial table-setup as well, not just for migrating from earlier versions.

A bit disturbing here is that the back trace is in istanbul; that should only be used in tests and should be excluded from loading otherwise.

**Comment by fiddur** [comment]
I tried a fresh install now, without migration, and I get a running listening express server, I get the "start page" on http://localhost:1337/ and it crashes when I try to go to the test page, since it tries to use the tables that aren't created.  So it seems your error is something else…

I don't have any unmet dependencies on `npm list`.  What node version are you using?  I remember having problems installing sqlite on node 0.12, so I have only used 0.10 for this.

**Comment by ostPavel** [comment]
Node v0.12.7

**Comment by fiddur** [comment]
So, it seems some more of the dependencies doesn't work on 0.12.  What packages do you have in the unmet-list?

**Comment by ostPavel** [comment]
Not sure where if Markdown has something to hide this wall of text :\

Here's what *npm list* shows

some-comments@0.2.0 /var/www/some-comments
├─┬ body-parser@1.13.3
│ ├── bytes@2.1.0
│ ├── content-type@1.0.1
│ ├─┬ debug@2.2.0
│ │ └── ms@0.7.1
│ ├── depd@1.0.1
│ ├─┬ http-errors@1.3.1
│ │ ├── inherits@2.0.1
│ │ └── statuses@1.2.1
│ ├── iconv-lite@0.4.11
│ ├─┬ on-finished@2.3.0
│ │ └── ee-first@1.1.1
│ ├── qs@4.0.0
│ ├─┬ raw-body@2.1.3
│ │ └── unpipe@1.0.0
│ └─┬ type-is@1.6.8
│   ├── media-typer@0.3.0
│   └─┬ mime-types@2.1.6
│     └── mime-db@1.18.0
├─┬ cookie-session@1.2.0
│ ├─┬ cookies@0.5.0
│ │ └── keygrip@1.0.1
│ ├─┬ debug@2.2.0
│ │ └── ms@0.7.1
│ └── on-headers@1.0.0
├─┬ cors@2.7.1
│ └── vary@1.0.1
├─┬ coveralls@2.11.4
│ ├─┬ js-yaml@3.0.1
│ │ ├─┬ argparse@0.1.16
│ │ │ ├── UNMET DEPENDENCY underscore@~1.7.0
│ │ │ └── UNMET DEPENDENCY underscore.string@~2.4.0
│ │ └── esprima@1.0.4
│ ├── lcov-parse@0.0.6
│ ├── log-driver@1.2.4
│ └─┬ request@2.40.0
│   ├── aws-sign2@0.5.0
│   ├── forever-agent@0.5.2
│   ├─┬ form-data@0.1.4
│   │ ├── UNMET DEPENDENCY async@~0.9.0
│   │ ├── UNMET DEPENDENCY combined-stream@~0.0.4
│   │ └── UNMET DEPENDENCY mime@~1.2.11
│   ├─┬ hawk@1.1.1
│   │ ├── UNMET DEPENDENCY boom@0.4.x
│   │ ├── UNMET DEPENDENCY cryptiles@0.2.x
│   │ ├── UNMET DEPENDENCY hoek@0.9.x
│   │ └── UNMET DEPENDENCY sntp@0.2.x
│   ├─┬ http-signature@0.10.1
│   │ ├── UNMET DEPENDENCY asn1@0.1.11
│   │ ├── UNMET DEPENDENCY assert-plus@^0.1.5
│   │ └── UNMET DEPENDENCY ctype@0.5.3
│   ├── json-stringify-safe@5.0.1
│   ├── mime-types@1.0.2
│   ├── node-uuid@1.4.3
│   ├── oauth-sign@0.3.0
│   ├── qs@1.0.2
│   ├── stringstream@0.0.4
│   ├── tough-cookie@2.0.0
│   └── tunnel-agent@0.4.1
├─┬ express@4.13.3
│ ├─┬ accepts@1.2.13
│ │ ├─┬ mime-types@2.1.6
│ │ │ └── mime-db@1.18.0
│ │ └── negotiator@0.5.3
│ ├── array-flatten@1.1.1
│ ├── content-disposition@0.5.0
│ ├── content-type@1.0.1
│ ├── cookie@0.1.3
│ ├── cookie-signature@1.0.6
│ ├─┬ debug@2.2.0
│ │ └── ms@0.7.1
│ ├── depd@1.0.1
│ ├── escape-html@1.0.2
│ ├── etag@1.7.0
│ ├─┬ finalhandler@0.4.0
│ │ └── unpipe@1.0.0
│ ├── fresh@0.3.0
│ ├── merge-descriptors@1.0.0
│ ├── methods@1.1.1
│ ├─┬ on-finished@2.3.0
│ │ └── ee-first@1.1.1
│ ├── parseurl@1.3.0
│ ├── path-to-regexp@0.1.7
│ ├─┬ proxy-addr@1.0.8
│ │ ├── forwarded@0.1.0
│ │ └── ipaddr.js@1.0.1
│ ├── qs@4.0.0
│ ├── range-parser@1.0.2
│ ├─┬ send@0.13.0
│ │ ├── destroy@1.0.3
│ │ ├─┬ http-errors@1.3.1
│ │ │ └── inherits@2.0.1
│ │ ├── mime@1.3.4
│ │ ├── ms@0.7.1
│ │ └── statuses@1.2.1
│ ├── serve-static@1.10.0
│ ├─┬ type-is@1.6.8
│ │ ├── media-typer@0.3.0
│ │ └─┬ mime-types@2.1.6
│ │   └── mime-db@1.18.0
│ ├── utils-merge@1.0.0
│ └── vary@1.0.1
├─┬ express-handlebars@2.0.1
│ ├─┬ glob@5.0.14
│ │ ├─┬ inflight@1.0.4
│ │ │ └── wrappy@1.0.1
│ │ ├── inherits@2.0.1
│ │ ├─┬ minimatch@2.0.10
│ │ │ └─┬ brace-expansion@1.1.0
│ │ │   ├── balanced-match@0.2.0
│ │ │   └── concat-map@0.0.1
│ │ ├─┬ once@1.3.2
│ │ │ └── wrappy@1.0.1
│ │ └── path-is-absolute@1.0.0
│ ├── graceful-fs@3.0.8
│ ├─┬ object.assign@1.1.1
│ │ └── object-keys@1.0.7
│ └─┬ promise@6.1.0
│   └── asap@1.0.0
├─┬ grunt@0.4.5
│ ├── async@0.1.22
│ ├── coffee-script@1.3.3
│ ├── colors@0.6.2
│ ├── dateformat@1.0.2-1.2.3
│ ├── eventemitter2@0.4.14
│ ├── exit@0.1.2
│ ├─┬ findup-sync@0.1.3
│ │ ├─┬ glob@3.2.11
│ │ │ ├── inherits@2.0.1
│ │ │ └─┬ minimatch@0.3.0
│ │ │   ├── UNMET DEPENDENCY lru-cache@2
│ │ │   └── UNMET DEPENDENCY sigmund@~1.0.0
│ │ └── lodash@2.4.2
│ ├── getobject@0.1.0
│ ├─┬ glob@3.1.21
│ │ ├── graceful-fs@1.2.3
│ │ └── inherits@1.0.2
│ ├─┬ grunt-legacy-log@0.1.2
│ │ ├── grunt-legacy-log-utils@0.1.1
│ │ ├── lodash@2.4.2
│ │ └── underscore.string@2.3.3
│ ├── grunt-legacy-util@0.2.0
│ ├── hooker@0.2.3
│ ├── iconv-lite@0.2.11
│ ├─┬ js-yaml@2.0.5
│ │ ├─┬ argparse@0.1.16
│ │ │ └── UNMET DEPENDENCY underscore@~1.7.0
│ │ └── esprima@1.0.4
│ ├── lodash@0.9.2
│ ├─┬ minimatch@0.2.14
│ │ ├── lru-cache@2.7.0
│ │ └── sigmund@1.0.1
│ ├─┬ nopt@1.0.10
│ │ └── abbrev@1.0.7
│ ├── rimraf@2.2.8
│ ├── underscore.string@2.2.1 invalid
│ └── which@1.0.9
├─┬ handlebars@3.0.3
│ ├── UNMET DEPENDENCY optimist@^0.6.1
│ └── UNMET DEPENDENCY source-map@^0.1.40
├─┬ istanbul@0.3.19
│ ├── abbrev@1.0.7
│ ├── async@1.4.2
│ ├─┬ escodegen@1.6.1
│ │ ├── UNMET DEPENDENCY estraverse@^1.9.1
│ │ ├── UNMET DEPENDENCY esutils@^1.1.6
│ │ └── UNMET DEPENDENCY optionator@^0.5.0
│ ├── esprima@2.5.0 invalid
│ ├─┬ fileset@0.2.1
│ │ ├── UNMET DEPENDENCY glob@5.x
│ │ └── UNMET DEPENDENCY minimatch@2.x
│ ├─┬ handlebars@3.0.0
│ │ ├── UNMET DEPENDENCY optimist@^0.6.1
│ │ └── UNMET DEPENDENCY source-map@^0.1.40
│ ├─┬ js-yaml@3.4.2
│ │ └── UNMET DEPENDENCY argparse@~1.0.2
│ ├─┬ mkdirp@0.5.1
│ │ └── UNMET DEPENDENCY minimist@0.0.8
│ ├── nopt@3.0.4
│ ├─┬ once@1.3.2
│ │ └── wrappy@1.0.1
│ ├── resolve@1.1.6
│ ├── supports-color@1.3.1
│ ├── which@1.0.9
│ └── wordwrap@0.0.3
├─┬ istanbul-middleware@0.2.0 (git+https://github.com/mcollina/istanbul-middleware.git#543e07caca3e91204af2561b805cf71a68f6d805)
│ ├─┬ archiver@0.14.4
│ │ ├── async@0.9.2
│ │ ├── buffer-crc32@0.2.5
│ │ ├─┬ glob@4.3.5
│ │ │ ├─┬ inflight@1.0.4
│ │ │ │ └── wrappy@1.0.1
│ │ │ ├── inherits@2.0.1
│ │ │ ├─┬ minimatch@2.0.10
│ │ │ │ └─┬ brace-expansion@1.1.0
│ │ │ │   ├── balanced-match@0.2.0
│ │ │ │   └── concat-map@0.0.1
│ │ │ └─┬ once@1.3.2
│ │ │   └── wrappy@1.0.1
│ │ ├── lazystream@0.1.0
│ │ ├── lodash@3.2.0
│ │ ├─┬ readable-stream@1.0.33
│ │ │ ├── core-util-is@1.0.1
│ │ │ ├── inherits@2.0.1
│ │ │ ├── isarray@0.0.1
│ │ │ └── string_decoder@0.10.31
│ │ ├─┬ tar-stream@1.1.5
│ │ │ ├── bl@0.9.4
│ │ │ ├─┬ end-of-stream@1.1.0
│ │ │ │ └─┬ once@1.3.2
│ │ │ │   └── wrappy@1.0.1
│ │ │ └── xtend@4.0.0
│ │ └─┬ zip-stream@0.5.2
│ │   └─┬ compress-commons@0.2.9
│ │     ├── crc32-stream@0.3.4
│ │     └── node-int64@0.3.3
│ └─┬ body-parser@1.12.4
│   ├── bytes@1.0.0
│   ├── content-type@1.0.1
│   ├─┬ debug@2.2.0
│   │ └── ms@0.7.1
│   ├── depd@1.0.1
│   ├── iconv-lite@0.4.8
│   ├─┬ on-finished@2.2.1
│   │ └── ee-first@1.1.0
│   ├── qs@2.4.2
│   ├─┬ raw-body@2.0.2
│   │ └── bytes@2.1.0
│   └─┬ type-is@1.6.8
│     ├── media-typer@0.3.0
│     └─┬ mime-types@2.1.6
│       └── mime-db@1.18.0
├─┬ jade@1.11.0
│ ├── character-parser@1.2.1
│ ├─┬ clean-css@3.4.1
│ │ └── UNMET DEPENDENCY source-map@0.4.x
│ ├── commander@2.6.0 invalid
│ ├─┬ constantinople@3.0.2
│ │ └── UNMET DEPENDENCY acorn@^2.1.0
│ ├─┬ jstransformer@0.0.2
│ │ ├── UNMET DEPENDENCY is-promise@^2.0.0
│ │ └── UNMET DEPENDENCY promise@^6.0.1
│ ├─┬ mkdirp@0.5.1
│ │ └── UNMET DEPENDENCY minimist@0.0.8
│ ├─┬ transformers@2.1.0
│ │ ├── UNMET DEPENDENCY css@~1.0.8
│ │ └── UNMET DEPENDENCY promise@~2.0
│ ├─┬ uglify-js@2.4.24 invalid
│ │ ├── UNMET DEPENDENCY async@~0.2.6
│ │ ├── UNMET DEPENDENCY source-map@0.1.34
│ │ ├── UNMET DEPENDENCY uglify-to-browserify@~1.0.0
│ │ └── UNMET DEPENDENCY yargs@~3.5.4
│ ├── void-elements@2.0.1
│ └─┬ with@4.0.3
│   ├── UNMET DEPENDENCY acorn@^1.0.1
│   └── UNMET DEPENDENCY acorn-globals@^1.0.3
├─┬ jsonwebtoken@5.0.5
│ └─┬ jws@3.1.0
│   ├─┬ base64url@1.0.4
│   │ ├─┬ concat-stream@1.4.10
│   │ │ ├── UNMET DEPENDENCY inherits@~2.0.1
│   │ │ ├── UNMET DEPENDENCY readable-stream@~1.1.9
│   │ │ └── UNMET DEPENDENCY typedarray@~0.0.5
│   │ └─┬ meow@2.0.0
│   │   ├── UNMET DEPENDENCY camelcase-keys@^1.0.0
│   │   ├── UNMET DEPENDENCY indent-string@^1.1.0
│   │   ├── UNMET DEPENDENCY minimist@^1.1.0
│   │   └── UNMET DEPENDENCY object-assign@^1.0.0
│   └─┬ jwa@1.1.0
│     ├── base64url@0.0.6
│     ├── buffer-equal-constant-time@1.0.1
│     └─┬ ecdsa-sig-formatter@1.0.2
│       ├── UNMET DEPENDENCY asn1.js@^2.0.3
│       └── UNMET DEPENDENCY base64-url@^1.2.1
├─┬ markdown@0.5.0
│ └─┬ nopt@2.1.2
│   └── abbrev@1.0.7
├─┬ migrate-orm2@1.2.14
│ ├── async@0.2.10
│ ├── lodash@2.4.2
│ ├── migrate@0.1.6
│ ├── mkdirp@0.3.5
│ └─┬ sql-ddl-sync@0.3.11 (git://github.com/dresende/node-sql-ddl-sync.git#a0ff01b48df28487c8cb662585fa42fa8b383ddd)
│   └── lodash@2.4.1
├─┬ mocha@2.3.2
│ ├── UNMET DEPENDENCY commander@2.3.0
│ ├── UNMET DEPENDENCY debug@2.0.0
│ ├── UNMET DEPENDENCY diff@1.4.0
│ ├── UNMET DEPENDENCY escape-string-regexp@1.0.2
│ ├── UNMET DEPENDENCY glob@3.2.3
│ ├── UNMET DEPENDENCY growl@1.8.1
│ ├── UNMET DEPENDENCY mkdirp@0.5.0
│ └── UNMET DEPENDENCY supports-color@1.2.0
├─┬ morgan@1.6.1
│ ├── basic-auth@1.0.3
│ ├─┬ debug@2.2.0
│ │ └── ms@0.7.1
│ ├── depd@1.0.1
│ ├─┬ on-finished@2.3.0
│ │ └── ee-first@1.1.1
│ └── on-headers@1.0.0
├─┬ nodemailer@1.4.0
│ ├─┬ buildmail@1.2.4
│ │ ├── addressparser@0.3.2
│ │ ├── libbase64@0.1.0
│ │ └── libqp@1.0.0
│ ├─┬ hyperquest@1.2.0
│ │ ├─┬ duplexer2@0.0.2
│ │ │ └─┬ readable-stream@1.1.13
│ │ │   ├── core-util-is@1.0.1
│ │ │   ├── inherits@2.0.1
│ │ │   ├── isarray@0.0.1
│ │ │   └── string_decoder@0.10.31
│ │ └─┬ through2@0.6.5
│ │   ├─┬ readable-stream@1.0.33
│ │   │ ├── core-util-is@1.0.1
│ │   │ ├── inherits@2.0.1
│ │   │ ├── isarray@0.0.1
│ │   │ └── string_decoder@0.10.31
│ │   └── xtend@4.0.0
│ ├─┬ libmime@1.0.0
│ │ ├── iconv-lite@0.4.11
│ │ ├── libbase64@0.1.0
│ │ └── libqp@1.0.0
│ ├─┬ nodemailer-direct-transport@1.0.2
│ │ └── smtp-connection@1.3.1
│ └─┬ nodemailer-smtp-transport@1.0.3
│   ├── clone@1.0.2
│   ├── nodemailer-wellknown@0.1.7
│   └── smtp-connection@1.3.1
├─┬ orm@2.1.27
│ ├── enforce@0.1.6
│ ├── hat@0.0.3
│ ├── lodash@2.4.1
│ ├── sql-ddl-sync@0.3.11
│ └── sql-query@0.1.26
├─┬ orm-migrate@1.0.5
│ ├─┬ commander@2.8.1
│ │ └── graceful-readlink@1.0.1
│ ├─┬ mysql@2.9.0
│ │ ├── UNMET DEPENDENCY bignumber.js@2.0.7
│ │ └── UNMET DEPENDENCY readable-stream@~1.1.13
│ ├─┬ pg@3.6.3
│ │ ├── UNMET DEPENDENCY bindings@1.2.1
│ │ ├── UNMET DEPENDENCY buffer-writer@1.0.0
│ │ ├── UNMET DEPENDENCY generic-pool@2.1.1
│ │ ├── UNMET DEPENDENCY nan@1.3.0
│ │ ├── UNMET DEPENDENCY packet-reader@0.2.0
│ │ ├── UNMET DEPENDENCY pg-connection-string@0.1.3
│ │ ├── UNMET DEPENDENCY pg-types@1.6.0
│ │ └── UNMET DEPENDENCY pgpass@0.0.3
│ └─┬ sql-ddl-sync@0.1.4
│   └── lodash@2.4.1
├── orm-timestamps@0.5.2
├─┬ passport@0.2.2
│ ├── passport-strategy@1.0.0
│ └── pause@0.0.1
├─┬ passport-facebook@2.0.0
│ └─┬ passport-oauth2@1.1.2
│   ├── oauth@0.9.13
│   ├── passport-strategy@1.0.0
│   └── uid2@0.0.3
├─┬ passport-github@0.1.5
│ ├─┬ passport-oauth@0.1.15
│ │ ├── oauth@0.9.13
│ │ └─┬ passport@0.1.18
│ │   └── pause@0.0.1
│ └── pkginfo@0.2.3
├─┬ passport-google-oauth2@0.1.6
│ └─┬ passport-oauth2@1.1.2
│   ├── oauth@0.9.13
│   ├── passport-strategy@1.0.0
│   └── uid2@0.0.3
├─┬ passport-openidconnect@0.0.1 (git+https://github.com/fiddur/passport-openidconnect.git#d6bdeef18e3c6e25e84bfc138d5ad9b43fcdfc9a)
│ ├── oauth@0.9.13
│ ├── pkginfo@0.3.0
│ └─┬ webfinger@0.4.2 (git://github.com/dwaite/webfinger.git#cce28c7b63f677f1f6839cf6b0c109017d0fdfd0)
│   ├── step@0.0.5
│   └─┬ xml2js@0.4.12
│     ├── sax@1.1.2
│     └─┬ xmlbuilder@3.0.0
│       └── lodash@3.10.1
├── q@1.4.1
├─┬ q-orm@0.0.1 (git://github.com/fiddur/q-orm.git#d5abc723aad10c57011e1a98a8859d20ed5fe5fe)
│ └── qx@1.0.0
├─┬ should@6.0.3
│ ├── should-equal@0.3.1
│ ├── should-format@0.0.7
│ └── should-type@0.0.4
└─┬ supertest@0.15.0
  ├── methods@1.1.1
  └─┬ superagent@0.21.0
    ├── component-emitter@1.1.2
    ├── cookiejar@2.0.1
    ├─┬ debug@2.2.0
    │ └── ms@0.7.1
    ├── extend@1.2.1
    ├─┬ form-data@0.1.3
    │ ├── async@0.9.2
    │ └─┬ combined-stream@0.0.7
    │   └── delayed-stream@0.0.5
    ├── formidable@1.0.14
    ├── methods@1.0.1
    ├── mime@1.2.11
    ├── qs@1.2.0
    ├─┬ readable-stream@1.0.27-1
    │ ├── core-util-is@1.0.1
    │ ├── inherits@2.0.1
    │ ├── isarray@0.0.1
    │ └── string_decoder@0.10.31
    └── reduce-component@1.0.1

npm ERR! missing: lru-cache@2, required by minimatch@0.3.0
npm ERR! missing: sigmund@~1.0.0, required by minimatch@0.3.0
npm ERR! invalid: underscore.string@2.2.1 /var/www/some-comments/node_modules/grunt/node_modules/underscore.string
npm ERR! missing: underscore@~1.7.0, required by argparse@0.1.16
npm ERR! missing: optimist@^0.6.1, required by handlebars@3.0.3
npm ERR! missing: source-map@^0.1.40, required by handlebars@3.0.3
npm ERR! missing: source-map@0.4.x, required by clean-css@3.4.1
npm ERR! invalid: commander@2.6.0 /var/www/some-comments/node_modules/jade/node_modules/commander
npm ERR! missing: acorn@^2.1.0, required by constantinople@3.0.2
npm ERR! missing: is-promise@^2.0.0, required by jstransformer@0.0.2
npm ERR! missing: promise@^6.0.1, required by jstransformer@0.0.2
npm ERR! missing: minimist@0.0.8, required by mkdirp@0.5.1
npm ERR! missing: promise@~2.0, required by transformers@2.1.0
npm ERR! missing: css@~1.0.8, required by transformers@2.1.0
npm ERR! invalid: uglify-js@2.4.24 /var/www/some-comments/node_modules/jade/node_modules/uglify-js
npm ERR! missing: async@~0.2.6, required by uglify-js@2.4.24
npm ERR! missing: source-map@0.1.34, required by uglify-js@2.4.24
npm ERR! missing: uglify-to-browserify@~1.0.0, required by uglify-js@2.4.24
npm ERR! missing: yargs@~3.5.4, required by uglify-js@2.4.24
npm ERR! missing: acorn@^1.0.1, required by with@4.0.3
npm ERR! missing: acorn-globals@^1.0.3, required by with@4.0.3
npm ERR! missing: inherits@~2.0.1, required by concat-stream@1.4.10
npm ERR! missing: typedarray@~0.0.5, required by concat-stream@1.4.10
npm ERR! missing: readable-stream@~1.1.9, required by concat-stream@1.4.10
npm ERR! missing: camelcase-keys@^1.0.0, required by meow@2.0.0
npm ERR! missing: indent-string@^1.1.0, required by meow@2.0.0
npm ERR! missing: minimist@^1.1.0, required by meow@2.0.0
npm ERR! missing: object-assign@^1.0.0, required by meow@2.0.0
npm ERR! missing: asn1.js@^2.0.3, required by ecdsa-sig-formatter@1.0.2
npm ERR! missing: base64-url@^1.2.1, required by ecdsa-sig-formatter@1.0.2
npm ERR! missing: bindings@1.2.1, required by pg@3.6.3
npm ERR! missing: buffer-writer@1.0.0, required by pg@3.6.3
npm ERR! missing: generic-pool@2.1.1, required by pg@3.6.3
npm ERR! missing: nan@1.3.0, required by pg@3.6.3
npm ERR! missing: packet-reader@0.2.0, required by pg@3.6.3
npm ERR! missing: pg-connection-string@0.1.3, required by pg@3.6.3
npm ERR! missing: pg-types@1.6.0, required by pg@3.6.3
npm ERR! missing: pgpass@0.0.3, required by pg@3.6.3
npm ERR! missing: bignumber.js@2.0.7, required by mysql@2.9.0
npm ERR! missing: readable-stream@~1.1.13, required by mysql@2.9.0
npm ERR! missing: commander@2.3.0, required by mocha@2.3.2
npm ERR! missing: debug@2.0.0, required by mocha@2.3.2
npm ERR! missing: diff@1.4.0, required by mocha@2.3.2
npm ERR! missing: escape-string-regexp@1.0.2, required by mocha@2.3.2
npm ERR! missing: glob@3.2.3, required by mocha@2.3.2
npm ERR! missing: growl@1.8.1, required by mocha@2.3.2
npm ERR! missing: mkdirp@0.5.0, required by mocha@2.3.2
npm ERR! missing: supports-color@1.2.0, required by mocha@2.3.2
npm ERR! invalid: esprima@2.5.0 /var/www/some-comments/node_modules/istanbul/node_modules/esprima
npm ERR! missing: estraverse@^1.9.1, required by escodegen@1.6.1
npm ERR! missing: esutils@^1.1.6, required by escodegen@1.6.1
npm ERR! missing: optionator@^0.5.0, required by escodegen@1.6.1
npm ERR! missing: optimist@^0.6.1, required by handlebars@3.0.0
npm ERR! missing: source-map@^0.1.40, required by handlebars@3.0.0
npm ERR! missing: minimist@0.0.8, required by mkdirp@0.5.1
npm ERR! missing: minimatch@2.x, required by fileset@0.2.1
npm ERR! missing: glob@5.x, required by fileset@0.2.1
npm ERR! missing: argparse@~1.0.2, required by js-yaml@3.4.2
npm ERR! missing: underscore@~1.7.0, required by argparse@0.1.16
npm ERR! missing: underscore.string@~2.4.0, required by argparse@0.1.16
npm ERR! missing: combined-stream@~0.0.4, required by form-data@0.1.4
npm ERR! missing: mime@~1.2.11, required by form-data@0.1.4
npm ERR! missing: async@~0.9.0, required by form-data@0.1.4
npm ERR! missing: assert-plus@^0.1.5, required by http-signature@0.10.1
npm ERR! missing: asn1@0.1.11, required by http-signature@0.10.1
npm ERR! missing: ctype@0.5.3, required by http-signature@0.10.1
npm ERR! missing: hoek@0.9.x, required by hawk@1.1.1
npm ERR! missing: boom@0.4.x, required by hawk@1.1.1
npm ERR! missing: cryptiles@0.2.x, required by hawk@1.1.1
npm ERR! missing: sntp@0.2.x, required by hawk@1.1.1

PS Bah, tried reinstalling, got this:

    root@Soundless:/var/www/some-comments# cd ..
    root@Soundless:/var/www# rm -r some-comments
    root@Soundless:/var/www# git clone https://github.com/fiddur/some-comments.git
    Cloning into 'some-comments'...
    remote: Counting objects: 581, done.
    remote: Compressing objects: 100% (33/33), done.
    remote: Total 581 (delta 13), reused 0 (delta 0), pack-reused 547
    Receiving objects: 100% (581/581), 141.89 KiB | 0 bytes/s, done.
    Resolving deltas: 100% (348/348), done.
    Checking connectivity... done.
    root@Soundless:/var/www# cd some-comments
    root@Soundless:/var/www/some-comments# npm install
    npm WARN package.json Dependency 'grunt' exists in both dependencies and devDependencies,     using 'grunt@^0.4.5' from dependencies

    > pg@3.6.3 install /var/www/some-comments/node_modules/orm-migrate/node_modules/pg
    > node-gyp rebuild || (exit 0)


    Killed

**Comment by fiddur** [comment]
Hmm, I need to clean up the dependencies.  Most of the missing dependencies are for the test frameworks.  pg in orm-migrate should not be needed unless you use postgres in the end.

I will look into making this work in newer versions of node, but right now I'd say use 0.10 if you're not inspired to dig into the dependencies yourself :)

**Comment by fiddur** [comment]
Now I've removed orm-migrate, that seemed to be the most offending.  I upgraded sqlite3 to version 3, and now it seems to work well with 0.12.

**Comment by ostPavel** [comment]
Thanks for a quick reply!
Using
    ` git clone -b fixDependencies https://github.com/fiddur/some-comments.git`

    root@Soundless:/var/www/some-comments# npm install
    npm ERR! Linux 3.13.0-57-generic
    npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
    npm ERR! node v0.12.7
    npm ERR! npm  v2.11.3
    npm ERR! code ENOMEM
    npm ERR! errno ENOMEM
    npm ERR! syscall spawn

    npm ERR! spawn ENOMEM
    npm ERR!
    npm ERR! If you need help, you may report this error at:
    npm ERR!     <https://github.com/npm/npm/issues>
    |
    > sqlite3@3.1.0 install /var/www/some-comments/node_modules/sqlite3
    > node-pre-gyp install --fallback-to-build
    root@Soundless:/var/www/some-comments#
    root@Soundless:/var/www/some-comments# cp config.js.example config.js
    root@Soundless:/var/www/some-comments# DB_URL=sqlite://data/comments.db
    root@Soundless:/var/www/some-comments# DB_URL=sqlite://data/comments.db ./node_modules/.bin/migrate up
    -bash: ./node_modules/.bin/migrate: No such file or directory
    root@Soundless:/var/www/some-comments# ./node_modules/.bin/migrate up
    -bash: ./node_modules/.bin/migrate: No such file or directory
    root@Soundless:/var/www/some-comments# node index.js
    
    /var/www/some-comments/node_modules/q/q.js:155
                    throw e;
                          ^
    ORMError: Connection protocol not supported - have you installed the database driver for sqlite?
        at Object.exports.connect (/var/www/some-comments/node_modules/orm/lib/ORM.js:141:21)
        at Promise.post (/var/www/some-comments/node_modules/q/q.js:1161:36)
        at Promise.promise.promiseDispatch (/var/www/some-comments/node_modules/q/q.js:788:41)
        at /var/www/some-comments/node_modules/q/q.js:1391:14
        at runSingle (/var/www/some-comments/node_modules/q/q.js:137:13)
        at flush (/var/www/some-comments/node_modules/q/q.js:125:13)
        at process._tickCallback (node.js:355:11)
        at Function.Module.runMain (module.js:503:11)
        at startup (node.js:129:16)
        at node.js:814:3
    root@Soundless:/var/www/some-comments#

I guess I derped with setting up the database, did I?

**Comment by fiddur** [comment]
Since I dropped orm-migrate, you have to use grunt to migrate, I'll remove the other option from README.

```
npm install -g grunt-cli
grunt migrate:up
```

But, it seems to fail installing sqlite3, even with the newer version.  That could be a problem with sqlite3 package, it should work in 0.12, but the binaries or binary builging depend on your machine I guess.  You could probably try `npm install sqlite3` and take any errors to the sqlite-team at https://github.com/mapbox/node-sqlite3

**Comment by ostPavel** [comment]
Looks like I am close to solving this!

    npm install
    npm install -g grunt-cli
    cp config.js.example config.js
    grunt migrate:up

produced 

    Warning: Connection protocol not supported - have you installed the database driver for sqlite? Use --force to continue.

    Aborted due to warnings.

Forcing sqlite3 to install (or to reinstall?):

    npm install
    npm install -g grunt-cli
    cp config.js.example config.js
    npm install sqlite3
    grunt migrate:up

Results in

    <...>
    migration : complete
    Done, without errors.

Now to properly set up the config and do the final testing.
Thanks again!

**Comment by ostPavel** [comment]
root@Soundless:/var/www/some-comments# node index.js
    Express server listening on port 1337 in development mode

This is it, I suppose!

**Comment by fiddur** [comment]
Congratulations!

I wonder why sqlite3 didn't install in the first run, but if it doesn't appear again, we could pretend it never happened :)
